name: Just Some Dev
description: Just some dev, blogging about programming
author: Ian Forsey
url: http://theon.github.io/blog/
permalink: /:title.html
pygments: true
paginate: 10
exclude: [themes]
disqus_sitename: justsomedev
google_analytics: UA-30513668-1